version: '3'
networks:
  lbs.net:
    driver: bridge
services:


  #####################################################
  # API GATEWAY
  #####################################################
  api.gateway:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.frontoffice.local
      - VHOST_DOCROOT=/var/www/public
    ports:
      - '19680:80'
      - '19643:443'
    volumes:
      - './LBS_Gateway_FrontOffice:/var/www/'
    working_dir: /var/www/
    networks:
      lbs.net:
        aliases:
          - api.gateway.local


  #######################################
  ###  Order Service : prise de commandes, suivi des commandes
  ###  api api.order
  ###  database gérée par le service mysql.order (sql)
  ###  requêtes HTTP vers api.catalog et api.fidelisation
  #######################################
  api.order:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.order.local
      - VHOST_DOCROOT=/var/www/public
    ports:
      - '19080:80'
      - '19043:443'
    volumes:
      - './LBS_Order-Service:/var/www'
    working_dir: /var/www/
    networks:
      lbs.net:
        aliases:
          - api.order.local
      
    depends_on:
      - order.db

  order.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=order001
      - MYSQL_USER=order_lbs
      - MYSQL_PASSWORD=order_lbs
      - MYSQL_DATABASE=order_lbs
    ports:
      - '3307:3306'
    networks:
      - lbs.net
    volumes:
      - './LBS_Order-Service/sql:/var/sql'

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - lbs.net


  ######################################
  ###  AUTH Service : service d'authentification JWT
  ###  api api.auth : auth, check, refresh de token JWT
  ###  utilise sa propre base de données
  ######################################
  api.auth:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.auth.local
      - VHOST_DOCROOT=/var/www/public
    ports:
      - '19780:80'
      - '19743:443'
    volumes:
      - './LBS_Auth-Service:/var/www'
    working_dir: /var/www/src
    networks:
      lbs.net:
        aliases:
          - api.auth.local
    depends_on:
      - mongo.auth


  ################################################
  # mongodb & mongo-express
  ###############################################
  mongo.auth:
    image: mongo:latest
    volumes:
      - ./LBS_Auth-Service/data:/var/data
    working_dir: /var/data
    networks:
      - lbs.net
    ports:
      - 27017:27017


  ###########################################################
  #
  #   Service catalogue, réalisé avec le CMS Headless Directus
  #   Service SQL géré par postgres
  #
  ###########################################################
  catalogue.data:
    image: postgis/postgis:13-master
    volumes:
      - ./lbs_catalogue_service/data/database:/var/lib/postgresql/data
    networks:
      - lbs.net
    environment:
      POSTGRES_USER: 'catalogue'
      POSTGRES_PASSWORD: 'catalogue'
      POSTGRES_DB: 'catalogue'

  api.catalogue:
    image: directus/directus:latest
    ports:
      - 19055:8055
    volumes:
      - ./lbs_catalogue_service/uploads:/directus/uploads
      - ./lbs_catalogue_service/extensions:/directus/extensions
    networks:
      - lbs.net
    depends_on:
      - catalogue.data
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'catalogue.data'
      DB_PORT: '5432'
      DB_DATABASE: 'catalogue'
      DB_USER: 'catalogue'
      DB_PASSWORD: 'catalogue'

      CACHE_ENABLED: 'false'
      ADMIN_EMAIL: 'admin@catalogue.net'
      ADMIN_PASSWORD: 'catalogue'


#######################################
###  backoffice : web wrapper html pour la gestion du catalogue
###  connexion avec l'api catalogue
#######################################
#  web.catalogue:
#    image: 'canals/php:latest'
#    environment:
#      - VHOST_HOSTNAME=web.catalogue.local
#      - VHOST_DOCROOT=/var/www/public
#    ports:
#      - '19480:80'
#      - '19443:443'
#    volumes:
#      - './lbs_catalogue_web/public:/var/www/public'
#      - './lbs_catalogue_web/src:/var/www/src'
#    working_dir: /var/www/src
#    networks:
#      - lbs.net
#    depends_on:
#      - api.catalogue
#
